server:
  port: 8091
spring:
  application:
    name: stream-service
  cloud:
    stream:
      bindings:
        default:
          destination: staging
          group-prefix: golden-unicorn
          binder: rabbit
        output:
          destination: staging
          binder: rabbit
      rabbit:
        bindings:
          input:
            consumer:
              binding-routing-key: entities.user
          output:
            producer:
              routing-key-expression: '"entities.user"'
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: springcloud
                password: 123456
                virtual-host: spring
logging:
  level:
    root: info